.firebase_authenticate_script: &firebase_authenticate_script
  - echo ${ARCHIVES_BASE_NAME}
  - echo $CLOUD_PROJECT_ID
  - gcloud config set project $CLOUD_PROJECT_ID
  - echo "$SERVICE_ACCOUNT" > /tmp/service-account.json
  - gcloud auth activate-service-account --key-file /tmp/service-account.json
  - APP="$APP_LOCATION"${ARCHIVES_BASE_NAME}-${APP_TYPE}
  - TEST_APP="$TEST_APP_LOCATION"${TEST_APP_BASE_NAME}-${TEST_APP_TYPE}
  - echo $APP
  - echo $TEST_APP
  - echo $PWD

.tests_preparation_script:
  stage: test
  tags:
    - shared-small
  except:
    - schedules
  variables:
    CHECKOUT_CORE_SUBMODULE: "true"
    NUM_SHARDS: 1
    TEST_APP_BASE_NAME: ${ARCHIVES_BASE_NAME}
  script:
    - *firebase_authenticate_script
    - date
    - gcloud --quiet beta firebase test android
      run firebase-device-config.yml:${TESTS_TYPE}
      --app "$APP"
      --timeout $TIMEOUT
      --test "$TEST_APP"
      --use-orchestrator
      --num-uniform-shards=${NUM_SHARDS}
      --num-flaky-test-attempts=2
      --environment-variables clearPackageData=true,useTestStorageService=true,coverage=true,coverageFilePath="/coverage/"
      --directories-to-pull /sdcard
      --test-targets "class $TEST_SUITE" 2>&1 | tee results.txt
    - echo gcloud end time
    - date
    - gcsbucket=$(cat results.txt | grep 'Raw results will be stored' | awk -F/ '{print "gs://" $6 "/" $7}')
    - echo $gcsbucket
    - if [ ! -z "$COVERAGE_FOLDER" ]; then
        gsutil ls $gcsbucket
          | grep '/$'
          | while read -r line; do
              dst=app/build/outputs/coverage/${COVERAGE_FOLDER}/`basename "$line"`;
              mkdir -p "$dst";
              gsutil -m cp ${line}artifacts/sdcard/googletest/internal_use/coverage/*.ec "$dst";
            done;
      fi
    - date
  artifacts:
    expire_in: 1 week
    paths:
      - app/build/outputs/

publish-apk-firebase:
  stage: startReview
  allow_failure: true
  tags:
    - shared-medium
  needs:
    - job: "build release firebase distribution"
    - job: "build google debug"
  only:
    - redesign-main
  except:
    - schedules
  script:
    - *firebase_authenticate_script
    - ./gradlew -q getReleaseNotes > release-notes.txt
    - cat release-notes.txt
    - wget --quiet --output-document=/tmp/firebase https://firebase.tools/bin/linux/latest
    - chmod +x /tmp/firebase
    - export GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account.json
    - /tmp/firebase appdistribution:distribute app/build/outputs/apk/productionGooglePlayStore/release/${ARCHIVES_BASE_NAME}-production-google-playStore-release.apk
      --app $FIREBASE_APP_ID
      --release-notes-file release-notes.txt
      --groups "dev-team"

mobile tests mocked api:
  extends: .tests_preparation_script
  variables:
    TESTS_TYPE: mobileTest
    NUM_SHARDS: 2
    APP_LOCATION: "app/build/outputs/apk/blackGooglePlayStore/debug/"
    APP_TYPE: "black-google-playStore-debug.apk"
    TEST_APP_LOCATION: "app/build/outputs/apk/androidTest/blackGooglePlayStore/debug/"
    TEST_APP_TYPE: "black-google-playStore-debug-androidTest.apk"
    TEST_SUITE: "com.protonvpn.testSuites.MobileMockApiSuite"
    TIMEOUT: $TIMEOUT_MOCKED_TESTS
#   UI coverage disabled for now due to API 23 devices crashing if running with coverage
#    COVERAGE_FOLDER: "mobile_mocked_api"

mobile tests test-env:
  extends: .tests_preparation_script
  variables:
    TESTS_TYPE: mobileTest
    NUM_SHARDS: 1
    APP_LOCATION: "app/build/outputs/apk/blackGooglePlayStore/debug/"
    APP_TYPE: "black-google-playStore-debug.apk"
    TEST_APP_LOCATION: "app/build/outputs/apk/androidTest/blackGooglePlayStore/debug/"
    TEST_APP_TYPE: "black-google-playStore-debug-androidTest.apk"
    TEST_SUITE: "com.protonvpn.testSuites.MobileBlackSuite"
    TIMEOUT: $TIMEOUT_GENERAL_TESTS
#    COVERAGE_FOLDER: "mobile_test_env"

tv tests:
  extends: .tests_preparation_script
  variables:
    TESTS_TYPE: tvTest
    APP_LOCATION: "app/build/outputs/apk/blackGooglePlayStore/debug/"
    APP_TYPE: "black-google-playStore-debug.apk"
    TEST_APP_LOCATION: "app/build/outputs/apk/androidTest/blackGooglePlayStore/debug/"
    TEST_APP_TYPE: "black-google-playStore-debug-androidTest.apk"
    TEST_SUITE: "com.protonvpn.testSuites.TvSuite"
    TIMEOUT: $TIMEOUT_GENERAL_TESTS
#    COVERAGE_FOLDER: "tv"

release tests:
  extends: .tests_preparation_script
  dependencies:
    - build google play dev (monitoring release)
    - build google debug # For ARCHIVES_BASE_NAME
  variables:
    TESTS_TYPE: smokeTest
    APP_LOCATION: "app/build/outputs/apk/productionGoogleDev/release/"
    APP_TYPE: "production-google-dev-release.apk"
    TEST_APP_LOCATION: "release_tests/build/outputs/apk/release/"
    TEST_APP_BASE_NAME: "release_tests"
    TEST_APP_TYPE: "release.apk"
    TEST_SUITE: "com.protonvpn.android.release_tests.suites.AllTests"
    TIMEOUT: $TIMEOUT_GENERAL_TESTS

robo tests:
  stage: test
  timeout: 2h
  needs:
    - build google play dev (monitoring release)
    - build google debug # For ARCHIVES_BASE_NAME
  tags:
    - shared-small
  rules:
    - if: $ROBO_TEST == "true"
      when: always
    - when: never
  script:
    - *firebase_authenticate_script
    - gcloud firebase test android run
      --type robo
      --app "$APP"
      --device model=Pixel2,version=30,locale=en,orientation=portrait
      --device model=Nexus6,version=24,locale=en,orientation=portrait
      --timeout $TIMEOUT
      --robo-script=gs://protonvpn-testing-scripts/ProtonVPN_Login_Robo_Script.json
      --robo-directives ignore:R.string.settings_sign_out=,ignore:R.string.settings_third_party_licenses=
  variables:
    TIMEOUT: $TIMEOUT_ROBO_TESTS
    APP_LOCATION: "app/build/outputs/apk/productionGoogleDev/release/"
    APP_TYPE: "production-google-dev-release.apk"
    CHECKOUT_CORE_SUBMODULE: "true"
  after_script:
    - |
      if [ $CI_JOB_STATUS == "failed" ]; then
        curl -X POST -H 'Content-type: application/json' --data "{"text":':warn: Scheduled robo tests failed: \n$CI_JOB_URL'}" "$SLACK_QA_HOOK"
      fi
