.firebase_authenticate_script: &firebase_authenticate_script
  - echo ${ARCHIVES_BASE_NAME}
  - echo $CLOUD_PROJECT_ID
  - gcloud config set project $CLOUD_PROJECT_ID
  - echo "$SERVICE_ACCOUNT" > /tmp/service-account.json
  - gcloud auth activate-service-account --key-file /tmp/service-account.json
  - APP="$APP_LOCATION"${ARCHIVES_BASE_NAME}-${APP_TYPE}
  - TEST_APP="$TEST_APP_LOCATION"${ARCHIVES_BASE_NAME}-${TEST_APP_TYPE}
  - echo $APP
  - echo $TEST_APP
  - echo $PWD

.tests_preparation_script:
  stage: test
  tags:
    - small
  except:
    - schedules
  variables:
    CHECKOUT_CORE_SUBMODULE: "true"
    NUM_SHARDS: 1
  script:
    - *firebase_authenticate_script
    - awk 'BEGIN { print strftime()  }'
    - gcloud --quiet beta firebase test android
      run firebase-device-config.yml:${TESTS_TYPE}
      --app "$APP"
      --test "$TEST_APP"
      --use-orchestrator
      --num-uniform-shards=${NUM_SHARDS}
      --num-flaky-test-attempts=2
      --environment-variables clearPackageData=true,useTestStorageService=true,coverage=true,coverageFilePath="/coverage/",listener=com.protonvpn.testsHelper.ToastingRunListener
      --directories-to-pull /sdcard
      --test-targets "class $TEST_SUITE" 2>&1 | tee results.txt
    - echo gcloud end time
    - awk 'BEGIN { print strftime()  }'
    - gcsbucket=$(cat results.txt | grep 'Raw results will be stored' | awk -F/ '{print "gs://" $6 "/" $7}')
    - echo $gcsbucket
    - if [ ! -z "$COVERAGE_FOLDER" ]; then
        gsutil ls $gcsbucket
          | grep '/$'
          | while read -r line; do
              dst=app/build/outputs/coverage/${COVERAGE_FOLDER}/`basename "$line"`;
              mkdir -p "$dst";
              gsutil -m cp ${line}artifacts/sdcard/googletest/internal_use/coverage/*.ec "$dst";
            done;
      fi
    - awk 'BEGIN { print strftime()  }'
  artifacts:
    expire_in: 1 week
    paths:
      - app/build/outputs/

mobile tests mocked api:
  extends: .tests_preparation_script
  variables:
    TESTS_TYPE: mobileTest
    NUM_SHARDS: 3
    APP_LOCATION: "app/build/outputs/apk/black/debug/"
    APP_TYPE: "black-debug.apk"
    TEST_APP_LOCATION: "app/build/outputs/apk/androidTest/black/debug/"
    TEST_APP_TYPE: "black-debug-androidTest.apk"
    TEST_SUITE: "com.protonvpn.testSuites.MobileMockApiSuite"
#    COVERAGE_FOLDER: "mobile_mocked_api"

mobile tests test-env:
  extends: .tests_preparation_script
  variables:
    TESTS_TYPE: mobileTest
    NUM_SHARDS: 1
    APP_LOCATION: "app/build/outputs/apk/black/debug/"
    APP_TYPE: "black-debug.apk"
    TEST_APP_LOCATION: "app/build/outputs/apk/androidTest/black/debug/"
    TEST_APP_TYPE: "black-debug-androidTest.apk"
    TEST_SUITE: "com.protonvpn.testSuites.MobileBlackSuite"
#    COVERAGE_FOLDER: "mobile_test_env"

tv tests:
  extends: .tests_preparation_script
  variables:
    TESTS_TYPE: tvTest
    APP_LOCATION: "app/build/outputs/apk/black/debug/"
    APP_TYPE: "black-debug.apk"
    TEST_APP_LOCATION: "app/build/outputs/apk/androidTest/black/debug/"
    TEST_APP_TYPE: "black-debug-androidTest.apk"
    TEST_SUITE: "com.protonvpn.testSuites.TvSuite"
#    COVERAGE_FOLDER: "tv"

real connection mobile tests:
  extends: .tests_preparation_script
  allow_failure: true
  variables:
    TESTS_TYPE: realConnectionTest
    APP_LOCATION: "app/build/outputs/apk/googlePlay/debug/"
    APP_TYPE: "googlePlay-debug.apk"
    TEST_APP_LOCATION: "app/build/outputs/apk/androidTest/googlePlay/debug/"
    TEST_APP_TYPE: "googlePlay-debug-androidTest.apk"
    TEST_SUITE: "com.protonvpn.testSuites.RealConnectionSuite"
#    COVERAGE_FOLDER: "real_connection"

robo tests:
  stage: test
  timeout: 1h 30m
  tags:
    - small
  rules:
    - if: $ROBO_TEST == "true"
      when: always
    - when: never
  script:
    - *firebase_authenticate_script
    - gcloud firebase test android run
      --type robo
      --app "$APP"
      --device model=Pixel2,version=30,locale=en,orientation=portrait
      --timeout $TIMEOUT
      --robo-script=gs://protonvpn-testing-scripts/ProtonVPN_Login_Robo_Script.json
      --robo-directives ignore:R.id.drawerButtonLogout=
  variables:
    TIMEOUT: 3600s
    APP_LOCATION: "app/build/outputs/apk/googlePlay/debug/"
    APP_TYPE: "googlePlay-debug.apk"
    CHECKOUT_CORE_SUBMODULE: "true"
  after_script:
    - | 
      if [ $CI_JOB_STATUS == "failed" ]; then
        curl -X POST -H 'Content-type: application/json' --data "{"text":':warn: Scheduled robo tests failed: \n$CI_JOB_URL'}" "$SLACK_QA_HOOK"
      fi